// <auto-generated />
using System;
using ControleFinanceiro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleFinanceiro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ControleFinanceiro.Domain.Entities.Category", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<string>("Color").IsRequired().HasMaxLength(20).HasColumnType("TEXT");
                b.Property<string>("Icon").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<bool>("IsDefault").HasColumnType("INTEGER");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<Guid?>("UserId").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Categories");

                b.HasData(
                    new { Id = new Guid("10000000-0000-0000-0000-000000000001"), Color = "#22C55E", Icon = "briefcase",    IsDefault = true, Name = "Salário" },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000002"), Color = "#10B981", Icon = "laptop",       IsDefault = true, Name = "Freelance" },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000003"), Color = "#059669", Icon = "trending-up",  IsDefault = true, Name = "Investimentos" },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000004"), Color = "#34D399", Icon = "plus-circle",  IsDefault = true, Name = "Outros (Receita)" },
                    new { Id = new Guid("20000000-0000-0000-0000-000000000001"), Color = "#F97316", Icon = "utensils",     IsDefault = true, Name = "Alimentação" },
                    new { Id = new Guid("20000000-0000-0000-0000-000000000002"), Color = "#3B82F6", Icon = "car",          IsDefault = true, Name = "Transporte" },
                    new { Id = new Guid("20000000-0000-0000-0000-000000000003"), Color = "#8B5CF6", Icon = "home",         IsDefault = true, Name = "Moradia" },
                    new { Id = new Guid("20000000-0000-0000-0000-000000000004"), Color = "#EF4444", Icon = "heart",        IsDefault = true, Name = "Saúde" },
                    new { Id = new Guid("20000000-0000-0000-0000-000000000005"), Color = "#F59E0B", Icon = "book",         IsDefault = true, Name = "Educação" },
                    new { Id = new Guid("20000000-0000-0000-0000-000000000006"), Color = "#EC4899", Icon = "gamepad",      IsDefault = true, Name = "Lazer" },
                    new { Id = new Guid("20000000-0000-0000-0000-000000000007"), Color = "#14B8A6", Icon = "shirt",        IsDefault = true, Name = "Vestuário" },
                    new { Id = new Guid("20000000-0000-0000-0000-000000000008"), Color = "#94A3B8", Icon = "minus-circle", IsDefault = true, Name = "Outros (Despesa)" });
            });

            modelBuilder.Entity("ControleFinanceiro.Domain.Entities.Transaction", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<decimal>("Amount").HasColumnType("decimal(18,2)");
                b.Property<Guid>("CategoryId").HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<DateTime>("Date").HasColumnType("TEXT");
                b.Property<string>("Description").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<bool>("IsRecurring").HasColumnType("INTEGER");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<int>("Type").HasColumnType("INTEGER");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("TEXT");
                b.Property<Guid>("UserId").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("CategoryId");
                b.HasIndex("UserId", "Date");
                b.ToTable("Transactions");
            });

            modelBuilder.Entity("ControleFinanceiro.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("ControleFinanceiro.Domain.Entities.Category", b =>
            {
                b.HasOne("ControleFinanceiro.Domain.Entities.User", "User")
                 .WithMany("Categories")
                 .HasForeignKey("UserId")
                 .OnDelete(DeleteBehavior.Cascade);
                b.Navigation("User");
            });

            modelBuilder.Entity("ControleFinanceiro.Domain.Entities.Transaction", b =>
            {
                b.HasOne("ControleFinanceiro.Domain.Entities.Category", "Category")
                 .WithMany("Transactions")
                 .HasForeignKey("CategoryId")
                 .OnDelete(DeleteBehavior.Restrict)
                 .IsRequired();
                b.HasOne("ControleFinanceiro.Domain.Entities.User", "User")
                 .WithMany("Transactions")
                 .HasForeignKey("UserId")
                 .OnDelete(DeleteBehavior.Cascade)
                 .IsRequired();
                b.Navigation("Category");
                b.Navigation("User");
            });

            modelBuilder.Entity("ControleFinanceiro.Domain.Entities.Category", b =>
            {
                b.Navigation("Transactions");
            });

            modelBuilder.Entity("ControleFinanceiro.Domain.Entities.User", b =>
            {
                b.Navigation("Categories");
                b.Navigation("Transactions");
            });
#pragma warning restore 612, 618
        }
    }
}
